version: "3.8"
services:

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    environment:
      - REDMINE_HOST=${REDMINE_HOST}
      - JENKINS_HOST=${JENKINS_HOST}
      - OVERLEAF_HOST=${OVERLEAF_HOST}

  certbot:
    image: certbot/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    depends_on:
      - nginx
      - redmine
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  redmine:
    image: redmine:latest
    restart: always
    ports:
      - 8888:3000
    environment:
      REDMINE_DB_POSTGRES: redmine_db
      REDMINE_DB_USERNAME: ${REDMINE_USERNAME}
      REDMINE_DB_PASSWORD: ${REDMINE_PASSWORD}
      REDMINE_PLUGIN_MIGRATE: 1
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
    depends_on:
      - redmine_db
      
  redmine_db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${REDMINE_PASSWORD}
      POSTGRES_USER: ${REDMINE_USERNAME}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  backup:
    build: ./backup
    volumes:
      - ./redmine/files:/data/redmine/files
      - ./jenkins:/data/jenkins
      - ./sharelatex/sharelatex:/data/sharelatex/sharelatex
      - ./sharelatex/redis:/data/sharelatex/redis
      - ./backup/archives:/backup/archives
    environment:
      REDMINE_USERNAME: ${REDMINE_USERNAME}
      REDMINE_PASSWORD: ${REDMINE_PASSWORD}

  s3sync:
    build: ./s3sync
    volumes:
      - ~/.aws:/root/.aws
      - ./backup/archives:/aws

  jenkins:
    image: jenkins/jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
    ports:
      - 8881:8080

  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - 8882:80
    links:
      - mongo
      - redis
    volumes:
      - ./sharelatex/sharelatex:/var/lib/sharelatex
    environment:
      SHARELATEX_APP_NAME: Overleaf Community Edition
      SHARELATEX_MONGO_URL: mongodb://mongo/sharelatex
      SHARELATEX_REDIS_HOST: redis
      REDIS_HOST: redis
      ENABLED_LINKED_FILE_TYPES: 'url,project_file'
      ENABLE_CONVERSIONS: 'true'
      EMAIL_CONFIRMATION_DISABLED: 'true'

      # temporary fix for LuaLaTex compiles
      # see https://github.com/overleaf/overleaf/issues/695
      TEXMFVAR: /var/lib/sharelatex/tmp/texmf-var

  mongo:
    restart: always
    image: mongo
#    expose:
#        - 27017
    volumes:
        - ./sharelatex/mongo:/data/db
    healthcheck:
        test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
        interval: 10s
        timeout: 10s
        retries: 5

  redis:
      restart: always
      image: redis:5
#      expose:
#          - 6379
      volumes:
          - ./sharelatex/redis:/data
